version: '3.8'

networks:
  simpleCRM:
    driver: bridge

services:
  mysql:
    networks:
      - simpleCRM
    platform: linux/x86_64
    container_name: simple-crm-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  mongodb:
    networks:
      - simpleCRM
    image: mongo
    container_name: simple-crm-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db

  nodejs:
    networks:
      - simpleCRM
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    command: [ "npm", "start" ]
    container_name: simple-crm-nodejs
    depends_on:
      - mysql
      - mongodb
    restart: always
    ports:
      - 7502:7502
    # specify a volume for live-reloading when source code change (in combination with nodemon)
    volumes:
      - ./nodejs/:/urs/src/app
