const DECORATOR_KEYS = {
    ROUTES: Symbol("ROUTES"),
    MODULES: Symbol("MODULES"),
    PROVIDERS: Symbol("PROVIDERS"),
    CONTROLLERS: Symbol("CONTROLLERS"),
    ROOT_PATH: Symbol("ROOT_PATH"),
    GUARD_MIDDLEWARES: Symbol("GUARD_MIDDLEWARES"),
    ERROR_MIDDLEWARES: Symbol("ERROR_MIDDLEWARES"),
}

export default DECORATOR_KEYS
