export { default as Employee } from "../modules/employees/employee.model"
export { default as Customer } from "../modules/customers/customer.model"
export { default as User } from "../modules/user/user.model"
export { default as Office } from "../modules/office/office.model"
export { default as Product } from "../modules/product/product.model"
