export { default as Employee } from "../modules/employees/employees.model"
export { default as Customer } from "../modules/customers/customer.model"
export { default as User } from "../modules/user/user.model"
export { default as Office } from "./office.model"
export { default as Product } from "./product.model"
